In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/esquilo/miniconda3/envs/directml/lib/python3.6/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [2]:
rank1_tensor = tf.Variable(["Test", "this", "is"],tf.string)
rank2_tensor = tf.Variable([["Test","this"],["is","only"]],tf.string)
print(rank1_tensor)
print(tf.rank(rank1_tensor))
print(rank1_tensor.shape)
print()
print(rank2_tensor)
print(tf.rank(rank2_tensor))
print(rank2_tensor.shape)

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'Test', b'this', b'is'], dtype=object)>
tf.Tensor(1, shape=(), dtype=int32)
(3,)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Test', b'this'],
       [b'is', b'only']], dtype=object)>
tf.Tensor(2, shape=(), dtype=int32)
(2, 2)


In [3]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor1, [3, -1])
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [5]:
print(tensor1.eval)
print(tensor2.eval)
print(tensor3.eval)

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>>
<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>>
<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>>
